### ISSUE TITLE
A question about ASPP

### ISSUE THREAD

**Issue by tianzhuotao** [ZHKKKe/PixelSSL#3]
Thanks for your great work for tackling the pixel-wise semi-supervised tasks. I am currently following it and I have the following question.

Should the returned value of 'out' at https://github.com/ZHKKKe/PixelSSL/blob/master/task/sseg/module/deeplab_v2.py#L85 be out of the for loop? Otherwise, the ASPP only adds the outputs of dilation rates 6 and 12.

Thanks in advance : )

**Comment by ZHKKKe** [comment]
Hi! Thanks for your attention!

Yes. It is a bug. 
Our code of DeepLabV2 is adapted from the repository: https://github.com/hfslyc/AdvSemiSeg. This bug is existing in their code (please check [here](https://github.com/hfslyc/AdvSemiSeg/blob/841d546c927605747594be726622363bf781cefb/model/deeplab.py#L116)).

In our ECCV work, we have found this problem and fixed it. The results are almost the same.
I am sorry that I forgot to fix this bug in the release version. 

The updated code and pre-trained models will be uploaded soon.

**Comment by tianzhuotao** [comment]
Thanks for your reply~

**Comment by ZHKKKe** [comment]
Hi, the bug is fixed and the new pre-trained models are available now!
